language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - TOXENV=django14
  - TOXENV=django15
  - TOXENV=django16
  - TOXENV=django17
  - TOXENV=django18
  - TOXENV=django19
  - TOXENV=django20

matrix:
  exclude:
    - python: 3.4
      env: TOXENV=django14
    - python: 3.5
      env: TOXENV=django14
    - python: 3.6
      env: TOXENV=django14

    - python: 3.5
      env: TOXENV=django15
    - python: 3.6
      env: TOXENV=django15

    - python: 3.5
      env: TOXENV=django16
    - python: 3.6
      env: TOXENV=django16

    - python: 3.5
      env: TOXENV=django17
    - python: 3.6
      env: TOXENV=django17

    - python: 2.7
      env: TOXENV=django20

script:
  - tox

install:
  - pip install tox
  - pip install factory_boy
  - pip install -e .

deploy:
  provider: pypi
  user: iwoca
  password:
    secure: KNgZPIZ8xv1sC5i8/NiNuUFe5Daae5iM4dz7tbAStxTvJ8W793ybxaIKL9EIFefAHwi7R9prqH+VBt2cu+td6x23OZyfbi3Ci6bpBmKjBCCPr6itMBNjuHOepvBIUWiBcewrQ6seeEdigKzKu53b5VS4zUT6mWOlwnOJV4RO4YY=
  on:
    tags: true
    all_branches: true
